import { 
  API_URL,
  API_KEY,
  TOP_ARTISTS_ENDPOINT,
  TOP_TRACKS_ENDPOINT
} from 'react-native-dotenv'

export default {
  API_URL,
  API_KEY,
  TOP_ARTISTS_ENDPOINT,
  TOP_TRACKS_ENDPOINT,
  SPLASH_DURATION: 3000,
  AXIOSTIMEOUT: 12000,
}
